databases:
  - name: XarpBP
    databaseName: sharpbp
    user: p3tyXVNTZPZT8XmvfeYaX7ZnIGxgdxF2

services:
  - type: web
    name: XarpBP
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    envVars:
      - key: postgres://sharpbp_user:p3tyXVNTZPZT8XmvfeYaX7ZnIGxgdxF2@dpg-cik0a55ph6euh7iv6asg-a.frankfurt-postgres.render.com/sharpbp
        fromDatabase:
          name: XarpBP
          property: connectionString
      - key: django-insecure-sz7l4=f%iycou#sz3*v5xs98sd70g54)%f3u6^6on!c9y!w*es
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
