# Generated by Django 4.2.1 on 2023-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
