# Generated by Django 4.2.1 on 2023-06-12 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0006_alter_userinfo_gender_alter_userinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_sys', models.IntegerField(blank=True, null=True)),
                ('bp_dia', models.IntegerField(blank=True, null=True)),
                ('bp_pulse', models.IntegerField(blank=True, null=True)),
                ('blood_sugar', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
