# Generated by Django 4.2.1 on 2023-06-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='readings',
            field=models.TextField(blank=True),
        ),
    ]
