# Generated by Django 4.2.1 on 2023-06-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_delete_patientreadingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreadings',
            name='title',
        ),
    ]
