# Generated by Django 4.2.1 on 2023-06-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_remove_patientreadings_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='readings',
        ),
    ]
