# Generated by Django 4.2.1 on 2023-07-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0015_userinfo_is_doctor_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='is_doctor',
            field=models.BooleanField(),
        ),
    ]
